name: build-and-push-to-registry
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker-container
      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: "${{ secrets.CONTAINER_REGISTRY_URL }}"
          username: "${{ secrets.CONTAINER_REGISTRY_USERNAME }}"
          password: "${{ secrets.CONTAINER_REGISTRY_PASSWORD }}"
      - name: Get repo name
        id: get-repo-name
        run: echo "::set-output name=value::$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')"
        shell: bash
      - name: Generate image tag
        id: generate-image-tag
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ secrets.CONTAINER_REGISTRY_URL }}/${{ steps.get-repo-name.outputs.value }}/web
          flavor: |
            latest=true
      - name: Cache image layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "${{ steps.generate-image-tag.outputs.tags }}"
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - name: Move cache
        # Temporary fix for excessive disk usage. For more details:
        # *   https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#local-cache
        # *   https://github.com/docker/build-push-action/issues/252
        # *   https://github.com/moby/buildkit/issues/1896
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
