name: build-and-push-to-registry
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: "${{ secrets.CONTAINER_REGISTRY_URL }}"
          username: "${{ secrets.CONTAINER_REGISTRY_USERNAME }}"
          password: "${{ secrets.CONTAINER_REGISTRY_PASSWORD }}"
      - name: Get repo name
        id: get-repo-name
        run: echo "::set-output name=value::$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')"
        shell: bash
      - name: Generate image tag
        id: generate-image-tag
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ secrets.CONTAINER_REGISTRY_URL }}/${{ steps.get-repo-name.outputs.value }}/web
          flavor: |
            latest=true
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "${{ steps.generate-image-tag.outputs.tags }}"
